{{ if .Values.blobfuseAccountName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.blobfuseAccountName }}-config
  namespace: {{ .Values.ns }}
type: azure/blobfuse
data:
  accountname: "{{ .Values.blobfuseAccountName | b64enc }}"
  accountkey: "{{ .Values.blobfuseAccountKey | b64enc }}"

{{ end }}