{{ if .Values.shareName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.storageName }}-config
  namespace: {{ .Values.ns }}
type: Opaque
data:
  azurestorageaccountname: "{{ .Values.accountName | b64enc }}"
  azurestorageaccountkey: "{{ .Values.accountKey | b64enc }}"

{{ end }}